import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <script async src="https://www.googletagmanager.com/gtag/js?id=AW-11301385971" />
      <script async src="/tag.js" />
      
      {/* <body>
        <div>hia</div>
      </body> */}
    </html>
  )
}
